### ISSUE TITLE
"check if you specified all information correctly"

### ISSUE THREAD

**Issue by jmieyt** [davidlinketech/instagram-account-generator#4]
idk why

**Comment by davidlinketech** [comment]
> IMPORTANT NOTE: Make sure to change the information around line 433 to yours. (sms API-key, Discord webhook...)

You have to change the information in line 433 to yours:
`t = threading.Thread(target=lambda h=i:instagen(h, smsapi="YOUR_SMS_API_KEY", country_code="DE", webhook="YOUR_DC_WEBHOOK"))`

**Comment by jmieyt** [comment]
i did

**Comment by davidlinketech** [comment]
show me how you did it
